version: '3.8'

services:
  n-docs:
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_DEV_MODE=true
      - NEXT_PUBLIC_DISABLE_DEVTOOLS=false
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev